export { default as AddProduct } from "./AddProduct";
export { default as Dashboard } from "./Dashboard";
export { default as OrderList } from "./OrderList";
export { default as ProductList } from "./ProductList";
export { default as ProcessOrder } from "./ProcessOrder";
export { default as ProductReviews } from "./ProductReviews";
export { default as UpdateProduct } from "./UpdateProduct";
export { default as UpdateUser } from "./UpdateUser";
export { default as UsersList } from "./UsersList";
